### PR TITLE
Fix leetcode-cn urls

### PR DESCRIPTION
**Pull request by zouyonghao**
It seems the leetcode-cn plugin need one more url replaced for working well.
That is ```config.sys.urls.problem_detail```

### CODE REVIEW

**Comment by jdneo** [comment]
I also have some problems when submitting answers to leetcode-cn. @zouyonghao May I ask what is this change fixing for?

**Comment by zouyonghao** [comment]
@jdneo If you install the leetcode.cn plugin, it works fine when you try login and list problems. But when you try to show the problem detail, it still use the leetcode.com, so I just add a replacement for the problem detail url.
ps. use ```leetcode show 1 -vv``` to see the process

**Comment by jdneo** [comment]
@zouyonghao Yes after adding this line everything works fine now.

Maybe a stupid question from me: I didn't find any place referencing the `sys.urls.problem_detail`. Just curious how this magic happen. 😄

**Comment by zouyonghao** [comment]
@jdneo I'm glad it works lol. Actually as a Java/C++ programmer or to say a fool in JS, I also see it as a magic. But I guess the url works in ```leetcode.js``` plugin and the ```getProblem``` method.
The recent code is using ```graphql``` url, but in the release, it still use ```problem_detail```, maybe it's better to update the release.
see this [commit](https://github.com/skygragon/leetcode-cli/commit/fc7a09b7efcdb1cc3a8bdd88b857c7bc1f8cc078#diff-d601b0204c27277af09f19dd9d2da7d3L125)

**Comment by jdneo** [comment]
@zouyonghao ok I see.

@skygragon Is there any plan to publish the new version of cli?

**Pull request merged**
